### ISSUE TITLE
Add cipher demo that uses a KDF and a currently unbroken cipher

### ISSUE THREAD

**Issue by Gloegg** [MHumm/DelphiEncryptionCompendium#37]
The simple cipher demo does not use a KDF to generate a key and instead uses a password that has the right length to be accepted by the used cipher. Since developers (myself included) often start with copying code from the demo, it would be cool, if there was a demo, that uses the library in a safe way with an unbroken cipher. 
The goal here is, that developers, which are new to cryptography or this library, won't end up with weak encryption in their projects.

**Comment by MHumm** [comment]
KDF is for generating a key from a password. It's not really about generating encryption keys, but it can be used for this purpose though. I'll think about it. KDF would bring in hashes and up to now I wanted to have separate demos for cipher related things and hash related ones in order to not make things too complicated for new users. But a new demo might make sense. Maybe...

**Comment by MHumm** [comment]
I changed the cipher of the console demo now, but not to AES as I might change AES handling a bit in 6.5 (but not in an incompatible way) and I added another console demo using KDF1 to improve key security. You can check it out in development branch already. But most likely 6.4.1 will be released this afternoon already.

**Comment by MHumm** [comment]
A new demo was added to 6.4.1 which was just released. I hope it's good enough for now.
