### ISSUE TITLE
Are there plans to support bcrypt ?

### ISSUE THREAD

**Issue by fastbike** [MHumm/DelphiEncryptionCompendium#44]
Are there plans to support the brypt hash for securing passwords. This has been deemed to be one of the safest ways of hashing them as it requires a Salt to be provided and also is self tuning so the speed remains relatively constant, even when  run on faster hardware.

More info at
https://auth0.com/blog/hashing-in-action-understanding-bcrypt/

Would be happy if this only supported Delphi 10.x and above.

**Comment by MHumm** [comment]
Plans refer to something in the future. So to be precise about your question: no, there are no such plans. Why not? Because it's already implemented! ;-) Just no in an official release yet. But you can find it in the current commit of the master branch or better use the latest commit of the development branch. I just commited the newest draft of the documentation because of your request.

Let me know if my implementation has any issues for you. Unit tests are in place so it should work as intended.

**Comment by fastbike** [comment]
Apologies, my fault for not searching through the code.  I've now found THash_BCrypt

Thanks, we can close the ticket
